[package]
name = "keep_wsl"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
futures-util = "0.3.31"
log = "0.4.22"
sysexits = "0.8.5"
tokio = { version = "1.42.0", features = ["full"] }
windows-service = { version = "0.7" }
